# Generated by Django 6.0.3 on 2026-04-29 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('yelp', 'Yelp'), ('csv', 'CSV Import'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('score_reasoning', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
